version: "3.8"
services:
  server:
    build: ./server
    ports:
      - 4000:4000
    container_name: cr34-backend

  client:
    build: ./client
    ports:
      - 80:3000
    stdin_open: true
    tty: true
    depends_on:
      - server
